// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: bcst_entergame.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace pb
{

    [global::ProtoBuf.ProtoContract(Name = @"Bcst_EntityEnter")]
    public partial class BcstEntityEnter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"spaceid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Spaceid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"entitys")]
        public global::System.Collections.Generic.List<Entity> Entitys { get; } = new global::System.Collections.Generic.List<Entity>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"Bcst_EntityLeave")]
    public partial class BcstEntityLeave : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"spaceid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Spaceid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"eids")]
        public global::System.Collections.Generic.List<string> Eids { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"Bcst_EntityMove")]
    public partial class BcstEntityMove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"spaceid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Spaceid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"eid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Eid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"position")]
        public Vector3 Position { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
