//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class Item :  Bright.Config.BeanBase 
{
    public Item(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        { if(!_json["price"].IsNumber) { throw new SerializationException(); }  Price = _json["price"]; }
        { if(!_json["upgrade_to_item_id"].IsNumber) { throw new SerializationException(); }  UpgradeToItemId = _json["upgrade_to_item_id"]; }
        { var _j = _json["expire_time"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  ExpireTime = _j; } } else { ExpireTime = null; } }
        { if(!_json["batch_useable"].IsBoolean) { throw new SerializationException(); }  BatchUseable = _json["batch_useable"]; }
        { if(!_json["quality"].IsNumber) { throw new SerializationException(); }  Quality = (Quality)_json["quality"].AsInt; }
        { if(!_json["exchange_stream"].IsObject) { throw new SerializationException(); }  ExchangeStream = ItemExchange.DeserializeItemExchange(_json["exchange_stream"]);  }
        { if(!_json["rewards_1"].IsObject) { throw new SerializationException(); }  Rewards1 = Reward.DeserializeReward(_json["rewards_1"]);  }
        { var __json0 = _json["rewards_2"]; if(!__json0.IsArray) { throw new SerializationException(); } Rewards2 = new System.Collections.Generic.List<Reward>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Reward __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = Reward.DeserializeReward(__e0);  }  Rewards2.Add(__v0); }   }
        { var __json0 = _json["exchange_list_1"]; if(!__json0.IsArray) { throw new SerializationException(); } ExchangeList1 = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  ExchangeList1.Add(__v0); }   }
        { var __json0 = _json["exchange_list_2"]; if(!__json0.IsArray) { throw new SerializationException(); } ExchangeList2 = new System.Collections.Generic.List<ItemExchange>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { ItemExchange __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = ItemExchange.DeserializeItemExchange(__e0);  }  ExchangeList2.Add(__v0); }   }
        PostInit();
    }

    public Item(int id, string name, string desc, int price, int upgrade_to_item_id, long? expire_time, bool batch_useable, Quality quality, ItemExchange exchange_stream, Reward rewards_1, System.Collections.Generic.List<Reward> rewards_2, System.Collections.Generic.List<ItemExchange> exchange_list_1, System.Collections.Generic.List<ItemExchange> exchange_list_2 ) 
    {
        this.Id = id;
        this.Name = name;
        this.Desc = desc;
        this.Price = price;
        this.UpgradeToItemId = upgrade_to_item_id;
        this.ExpireTime = expire_time;
        this.BatchUseable = batch_useable;
        this.Quality = quality;
        this.ExchangeStream = exchange_stream;
        this.Rewards1 = rewards_1;
        this.Rewards2 = rewards_2;
        this.ExchangeList1 = exchange_list_1;
        this.ExchangeList2 = exchange_list_2;
        PostInit();
    }

    public static Item DeserializeItem(JSONNode _json)
    {
        return new Item(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 价格
    /// </summary>
    public int Price { get; private set; }
    /// <summary>
    /// 引用当前表
    /// </summary>
    public int UpgradeToItemId { get; private set; }
    public Item UpgradeToItemId_Ref { get; private set; }
    /// <summary>
    /// 过期时间
    /// </summary>
    public long? ExpireTime { get; private set; }
    /// <summary>
    /// 能否批量使用
    /// </summary>
    public bool BatchUseable { get; private set; }
    /// <summary>
    /// 品质
    /// </summary>
    public Quality Quality { get; private set; }
    /// <summary>
    /// 道具兑换配置
    /// </summary>
    public ItemExchange ExchangeStream { get; private set; }
    /// <summary>
    /// 奖励
    /// </summary>
    public Reward Rewards1 { get; private set; }
    /// <summary>
    /// 奖励列表
    /// </summary>
    public System.Collections.Generic.List<Reward> Rewards2 { get; private set; }
    /// <summary>
    /// 道具兑换配置列表1
    /// </summary>
    public System.Collections.Generic.List<ItemExchange> ExchangeList1 { get; private set; }
    /// <summary>
    /// 道具兑换配置列表2
    /// </summary>
    public System.Collections.Generic.List<ItemExchange> ExchangeList2 { get; private set; }

    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.UpgradeToItemId_Ref = (_tables["TbItem"] as TbItem).GetOrDefault(UpgradeToItemId);
        ExchangeStream?.Resolve(_tables);
        Rewards1?.Resolve(_tables);
        foreach(var _e in Rewards2) { _e?.Resolve(_tables); }
        foreach(var _e in ExchangeList1) { _e?.Resolve(_tables); }
        foreach(var _e in ExchangeList2) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        ExchangeStream?.TranslateText(translator);
        Rewards1?.TranslateText(translator);
        foreach(var _e in Rewards2) { _e?.TranslateText(translator); }
        foreach(var _e in ExchangeList1) { _e?.TranslateText(translator); }
        foreach(var _e in ExchangeList2) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Price:" + Price + ","
        + "UpgradeToItemId:" + UpgradeToItemId + ","
        + "ExpireTime:" + ExpireTime + ","
        + "BatchUseable:" + BatchUseable + ","
        + "Quality:" + Quality + ","
        + "ExchangeStream:" + ExchangeStream + ","
        + "Rewards1:" + Rewards1 + ","
        + "Rewards2:" + Bright.Common.StringUtil.CollectionToString(Rewards2) + ","
        + "ExchangeList1:" + Bright.Common.StringUtil.CollectionToString(ExchangeList1) + ","
        + "ExchangeList2:" + Bright.Common.StringUtil.CollectionToString(ExchangeList2) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
