//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class Reward :  Bright.Config.BeanBase 
{
    public Reward(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Count = _buf.ReadInt();
        Type = (RewardType)_buf.ReadInt();
        PostInit();
    }

    public static Reward DeserializeReward(ByteBuf _buf)
    {
        return new Reward(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 数量
    /// </summary>
    public int Count { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public RewardType Type { get; private set; }

    public const int __ID__ = -1850459313;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Count:" + Count + ","
        + "Type:" + Type + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}