//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace cfg
{ 
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbTest TbTest {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbItem = new TbItem(loader("tbitem")); 
        tables.Add("TbItem", TbItem);
        TbTest = new TbTest(loader("tbtest")); 
        tables.Add("TbTest", TbTest);

        PostInit();
        TbItem.Resolve(tables); 
        TbTest.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItem.TranslateText(translator); 
        TbTest.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}