//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
   
public partial class TbTest
{
    private readonly List<Test> _dataList;

    private Dictionary<(int, int), Test> _dataMapUnion;

    public TbTest(ByteBuf _buf)
    {
        _dataList = new List<Test>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Test _v;
            _v = Test.DeserializeTest(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(int, int), Test>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Key1, _v.Key2), _v);
        }
        PostInit();
    }


    public List<Test> DataList => _dataList;

    public Test Get(int key1, int key2) => _dataMapUnion.TryGetValue((key1, key2), out Test __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}