//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class Test :  Bright.Config.BeanBase 
{
    public Test(ByteBuf _buf) 
    {
        Key1 = _buf.ReadInt();
        Key2 = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new System.Collections.Generic.List<Reward>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Reward _e0;  _e0 = Reward.DeserializeReward(_buf); Rewards.Add(_e0);}}
        PostInit();
    }

    public static Test DeserializeTest(ByteBuf _buf)
    {
        return new Test(_buf);
    }

    public int Key1 { get; private set; }
    public int Key2 { get; private set; }
    /// <summary>
    /// 奖励列表
    /// </summary>
    public System.Collections.Generic.List<Reward> Rewards { get; private set; }

    public const int __ID__ = 2603186;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Rewards) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Rewards) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Key1:" + Key1 + ","
        + "Key2:" + Key2 + ","
        + "Rewards:" + Bright.Common.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}