
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg.demo
{

public partial class Tbitem
{
    private readonly System.Collections.Generic.Dictionary<int, demo.item> _dataMap;
    private readonly System.Collections.Generic.List<demo.item> _dataList;
    
    public Tbitem(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, demo.item>(_buf.Count);
        _dataList = new System.Collections.Generic.List<demo.item>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            demo.item _v;
            _v = global::cfg.demo.item.Deserializeitem(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, demo.item> DataMap => _dataMap;
    public System.Collections.Generic.List<demo.item> DataList => _dataList;

    public demo.item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public demo.item Get(int key) => _dataMap[key];
    public demo.item this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

