// Generated by https://github.com/xhaoh94/PbTool
// DO NOT EDIT!
namespace Pb
{
	public static partial class BCST
	{
		public const uint Bcst_EntityEnter = 30001;
		public const uint Bcst_EntityLeave = 30002;
		public const uint Bcst_EntityMove = 30003;
	}
}
