// Generated by https://github.com/xhaoh94/PbTool
// DO NOT EDIT!
namespace Pb
{
	public static partial class BCST
	{
		public const uint Bcst_UnitIntoView = 999900001;
		public const uint Bcst_UnitOutofView = 999900002;
		public const uint Bcst_UnitMove = 999900003;
		public const uint Bcst_UnitUpdatePosition = 999900004;
	}
}
