// Generated by https://github.com/xhaoh94/PbTool
// DO NOT EDIT!
namespace Pb
{
	public static partial class BCST
	{
		public const uint Bcst_EnterMap = 500200001;
		public const uint Bcst_LeaveMap = 500200002;
		public const uint Bcst_Move = 500200003;
	}
}
