// Generated by https://github.com/xhaoh94/PbTool
// DO NOT EDIT!
namespace Pb
{
	public static partial class CS
	{
		public const uint C2S_EnterGame = 10005;
		public const uint C2S_RegisterAccount = 10001;
		public const uint C2S_LoginGame = 10002;
		public const uint C2S_RoleList = 10003;
		public const uint C2S_CreateRole = 10004;
	}
}
