// Generated by https://github.com/xhaoh94/PbTool
// DO NOT EDIT!
namespace Pb
{
	public enum CS
	{
		C2S_EnterGame = 10005,
		C2S_RegisterAccount = 10001,
		C2S_LoginGame = 10002,
		C2S_RoleList = 10003,
		C2S_CreateRole = 10004,
	}
}
