// Generated by https://github.com/xhaoh94/PbTool
// DO NOT EDIT!
namespace Pb
{
	public static partial class CS
	{
		public const uint C2S_LoginGame = 100100001;
		public const uint C2S_EnterScene = 100200001;
		public const uint C2S_LeaveScene = 100200002;
		public const uint C2S_Move = 100200003;
	}
}
