// Generated by https://github.com/xhaoh94/PbTool
// DO NOT EDIT!
namespace Pb
{
	public enum SC
	{
		S2C_EnterGame = 10005,
		S2C_RegisterAccount = 10001,
		S2C_LoginGame = 10002,
		S2C_RoleList = 10003,
		S2C_CreateRole = 10004,
	}
}
