// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: errcode.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace pb
{

    [global::ProtoBuf.ProtoContract()]
    public enum ErrCode
    {
        Success = 0,
        UserNotFound = 1,
        PasswordError = 2,
        UserAlready = 3,
        RoleAlready = 4,
        UnKnown = 5,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
